name: Azure Functions CI/CD

# This is the main CI/CD pipeline for ODW Azure Functions
parameters:
# User-specified environment to deploy to
- name: env
  default: 'build'
  values:
  - 'build'
  - 'dev'
  - 'test'
  - 'prod'

# Run when Pull Request raised to the main branch
pr:
- main

# Run when merged into main
trigger:
 branches:
  include:
  - main

variables:
- name: env
  ${{ if and(eq(variables['Build.Reason'], 'IndividualCI'), and(eq(variables['Build.SourceBranch'], 'refs/heads/main')) }}:
    value: test
  ${{ else }}:
    value: ${{ parameters.env }}
- name: variableGroupName
  ${{ if eq(variables.env, 'prod') }}:
    value: "Terraform Prod"
  ${{ elseif eq(variables.env, 'test') }}:
    value: "Terraform Test"
  ${{ elseif eq(variables.env, 'build') }}:
    value: "Terraform Build"
  ${{ else }}:
    value: "Terraform Dev"
- name: agentPool
  value: 'pins-agent-pool-odw-${{ variables.env }}-uks'
- group: ${{ variables.variableGroupName }}

stages:
- stage:
  displayName: "test stage"
  jobs:
  - job:
    displayName: "test job"
    steps:
    - script: |
        echo "The build reason is set to ${{ variables.buildReason }}"
      displayName: 'test step'

- template: stages/wait-for-approval.yaml

- template: stages/deploy-function-app.yaml
  parameters:
    agentPool: ${{ variables.agentPool }}
    env: ${{ variables.env }}
